server:
  port: 8088

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/mapDB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
